import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
    name: '网上邻居',
    desc: '哔——啵——电波通讯中，欢迎常来串门。',
    entries: [{
        author: '张洪Heo',
        desc: '分享设计与科技生活',
        link: 'https://blog.zhheo.com/',
        feed: 'https://blog.zhheo.com/atom.xml',
        icon: 'https://blog.zhheo.com/img/favicon4.0.webp',
        avatar: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png',
        archs: ['Hexo', '国内 CDN'],
        date: '2024-02-02',
        comment: '知名博主，其博客设计风格被众多人借鉴。',
    }, {
        author: '天翔TNXG',
        sitenick: '空间站',
        title: '天翔TNXGの空间站',
        desc: '明日尚未到来，希望凝于心上',
        link: 'https://tnxgmoe.com/',
        feed: 'https://tnxgmoe.com/feed',
        icon: 'https://tnxgmoe.com/favicon.png',
        avatar: 'https://api-space.tnxg.top/avatar?s=qq',
        archs: ['Mix Space', 'Cloudflare'],
        date: '2024-07-11',
        comment: '西北地区高中生，开源爱好者。',
    }, {
        author: 'Leonus',
        title: 'Leonus',
        desc: '进一寸有进一寸的欢喜',
        link: 'https://blog.leonus.cn/',
        feed: 'https://blog.leonus.cn/atom.xml',
        icon: 'https://q1.qlogo.cn/g?b=qq&nk=553344777&s=5',
        archs: ['Hexo', 'CDN (国内)'],
        date: '2024-10-03',
        comment: '用Butterfly主题时遇到的大佬。',
    }, {
        author: 'Akilar',
        title: 'Akilar',
        desc: '欢迎光临糖果屋',
        link: 'https://akilar.top/',
        feed: 'https://akilar.top/atom.xml',
        icon: 'https://npm.elemecdn.com/akilar-candyassets/image/siteicon/favicon.png',
        archs: ['Hexo', 'CDN (国内)'],
        date: '2024-10-03',
        comment: '糖果屋的建立者，被网友称为‘店长’。',
    }, {
        author: '葱苓',
        sitenick: '语畔',
        title: '葱苓语畔',
        desc: 'Don\'t worry, be happy.',
        link: 'https://blog.ciraos.top/',
        feed: 'https://blog.ciraos.top/feed.xml',
        icon: 'https://blog.ciraos.top/avatar.avif',
        avatar: 'https://blog.ciraos.top/avatar.avif',
        archs: ['Next.js', '国内 CDN'],
        date: '2025-03-28',
        comment: '前端学习。',
    }, {
        author: 'Zkeq',
        title: 'Zkeq の Coding 日志',
        desc: '自强，弘毅，求实',
        link: 'https://icodeq.com/',
        feed: 'https://icodeq.com/atom.xml',
        icon: 'https://img.onmicrosoft.cn/Avatar.jpg',
        archs: ['Hexo', 'Vercel'],
        date: '2024-10-03',
        comment: '之前认识的前端大佬',
        avatar: 'https://img.onmicrosoft.cn/Avatar.jpg'
    }, {
        author: 'zxalive',
        title: '知行博客',
        desc: 'Java开发代码实战，搜你所需，快速CV，早点下班～',
        link: 'https://zxalive.com/',
        icon: 'https://zxalive.com/avatar.webp',
        archs: ['Halo', 'CDN (国内)'],
        date: '2024-10-03',
        avatar: 'https://zxalive.com/avatar.webp',
    }, {
        author: 'Liu Zijian',
        title: 'Liu Zijian’s Blog',
        desc: '道阻且长，行则将至',
        link: 'https://blog.liuzijian.com',
        icon: 'https://blog.liuzijian.com/img/logo.jpg',
        avatar: 'https://blog.liuzijian.com/img/logo.jpg',
        archs: ['Hexo', 'CDN (国内)'],
        date: '2024-10-26',
    }, {
        author: 'iFluxArt',
        desc: '斐启智境 · 流韵新生',
        link: 'https://iflux.art/',
        icon: 'https://iflux.art/favicon.ico',
        avatar: 'https://iflux.art/favicon.ico',
        archs: ['Next.js', 'Vercel'],
        date: '2025-04-16',
        comment: '文档型知识库，含AIGC、开发、设计、运营、传媒、工具等内容。',
    }, {
        author: 'Pinpe 的云端',
        desc: '一个属于自己的云朵',
        link: 'https://pinpe.top',
        icon: 'https://pinpe.top/head.jpg',
        avatar: 'https://pinpe.top/head.jpg',
        archs: ['WordPress', '服务器'],
        date: '2025-05-02',
        comment: '介绍 一个属于自己的云朵。',
    }, {
        author: '粥粥',
        desc: '我思故我在',
        link: 'https://www.illusional.top',
        icon: 'https://www.illusional.top/upload/fba2e09a430e024c585fbf5da748b02.jpg',
        avatar: 'https://www.illusional.top/upload/fba2e09a430e024c585fbf5da748b02.jpg',
        archs: ['Halo', '服务器'],
        date: '2025-05-18',
        comment: '我思故我在。',
    },],
}] satisfies FeedGroup[]